import { createPinia, setActivePinia } from 'pinia';
import { beforeEach, describe, expect, it } from 'vitest';
import { useBaseStore } from '../base';

// The store's public surface is consumed by 26 files through ~990 direct property
// accesses, so it is a contract rather than an implementation detail. This list was
// captured from the store before it was converted from the options API to a setup
// store, and pins that conversion to changing nothing observable: a member that is
// dropped, renamed, or turns from a value into a function (or back) fails here.
// Update it deliberately - only when a member is genuinely meant to be added or removed.
const PUBLIC_SURFACE = [
  'afterDoneAnimationEnd:boolean',
  'afterDoneCount:number',
  'arrayLength:number',
  'beforeMove:function',
  'blitzInterval:number',
  'blitzMovesCount:number',
  'blitzScrambleCount:number',
  'blitzTime:number',
  'blitzTimeStr:string',
  'boardPos:object',
  'boardSize:function',
  'cageCompleteImgLoaded:boolean',
  'cageHardcoreMode:boolean',
  'cageImageUrl:function',
  'cageImgIndex:number',
  'cageMode:boolean',
  'cagePath:string',
  'cagesCount:number',
  'canKeepSession:boolean',
  'cannotClick:boolean',
  'checkDiffBetweenElementsAndMove:function',
  'checkUserScrambleInDB:boolean',
  'clearDisplay:boolean',
  'clearMarathonData:function',
  'clearStoredSession:function',
  'consecutiveSolves:number',
  'currentAverages:object',
  'currentOrders:object',
  'darkMode:boolean',
  'disableDuringMarathon:boolean',
  'disableWinMessage:boolean',
  'doneFirstMove:boolean',
  'doPrepareCageMode:function',
  'doResetList:boolean',
  'enableCageMode:boolean',
  'fastWalkMode:boolean',
  'finishLoadingAllCageImages:boolean',
  'fmcBlitz:boolean',
  'fmcBlitzMovesRecord:number',
  'freeElementCol:number',
  'freeElementIndex:number',
  'freeElementRow:number',
  'g1000Mode:boolean',
  'getControlTypeStr:string',
  'getFMCBlitzScrambleCount:function',
  'getNextG1000:function',
  'getTime:number',
  'hideCurrentAverages:boolean',
  'hoverOnControl:boolean',
  'incConsecutiveSolves:function',
  'incMoves:function',
  'initAfterNewPuzzleSize:function',
  'initStore:function',
  'inPlaceCount:number',
  'inReplay:boolean',
  'interval:number',
  'invertPaused:function',
  'isDone:boolean',
  'isFetching:boolean',
  'isMoving:boolean',
  'isNetworkError:boolean',
  'isTimeFailed:boolean',
  'keepSession:boolean',
  'lastError:string',
  'lastGameID:string',
  'linkError:string',
  'loadAverages:function',
  'loadedCageImages:object',
  'loadFMCBlitzMovesRecord:function',
  'loadMovesRecord:function',
  'loadRecordFromLocalStorage:function',
  'loadTimeRecord:function',
  'loadUnlockedCagesFromLocalStorage:function',
  'marathonFirstMove:boolean',
  'marathonMode:boolean',
  'marathonReplay:boolean',
  'marathonScrambles:string',
  'marathonSolves:string',
  'markCageImageLoaded:function',
  'mixAndCheckSolvable:function',
  'mixedOrders:object',
  'moveDoneBy:number',
  'moveDown:function',
  'moveLeft:function',
  'moveRight:function',
  'movesCount:number',
  'movesRecord:number',
  'movesRecordTime:number',
  'moveUp:function',
  'newFMCBlitzMovesRecord:boolean',
  'newMovesRecord:boolean',
  'newPlaygroundMovesRecord:boolean',
  'newPlaygroundTimeRecord:boolean',
  'newTimeRecord:boolean',
  'nextMarathonReplayPuzzle:function',
  'noBordersInCageMode:boolean',
  'noPlayMode:boolean',
  'numLines:number',
  'opt_m:number',
  'otherUserName:string',
  'paused:boolean',
  'playgroundBestMoves:number',
  'playgroundBestTime:number',
  'playgroundBestTimeMoves:number',
  'playgroundCreatedAt:undefined',
  'playgroundMode:boolean',
  'playgroundModeRenew:function',
  'playgroundSolvePath:object',
  'preloadImage:function',
  'prevAverages:object',
  'proBeforeCage:boolean',
  'processingReInit:boolean',
  'proMode:boolean',
  'publicId:string',
  'puzzleLoaded:boolean',
  'registered:boolean',
  'renewPuzzle:function',
  'repGame:object',
  'replayMode:boolean',
  'replaySpeed:number',
  'reset:function',
  'resetConsecutiveSolves:function',
  'resetUnsolvedPuzzleWithEsc:boolean',
  'restartInterval:function',
  'restoreStoredSession:function',
  'safeLoadRecord:function',
  'savedOrders:object',
  'savedTime:number',
  'saveState:function',
  'saveTime:function',
  'sessionId:undefined',
  'setCurrentAverages:function',
  'setFMCBlitzRecord:function',
  'setMovesRecord:function',
  'setPuzzleData:function',
  'setRecords:function',
  'setSessionId:function',
  'setSpaceBetween:function',
  'setTimeRecord:function',
  'setUnlockedCages:function',
  'setWasAvgRecords:function',
  'sharedPlaygroundMode:boolean',
  'showAddScramble:boolean',
  'showConfig:boolean',
  'showImageGallery:boolean',
  'showInfo:boolean',
  'showLeaderBoard:boolean',
  'showLiveRecords:boolean',
  'showModal:boolean',
  'shownCages:object',
  'showOnlyUnlockedItems:boolean',
  'showRegModal:boolean',
  'showScrambleList:boolean',
  'showUserAccount:boolean',
  'showWinModal:boolean',
  'solvedPuzzlesInMarathon:number',
  'solvePath:object',
  'spaceBetween:number',
  'startBlitzTime:number',
  'startOrderedCount:number',
  'startTime:number',
  'stopBlitzInterval:function',
  'stopInterval:function',
  'storeRecord:function',
  'time:number',
  'timeMRecord:string',
  'timeRecord:number',
  'timeRecordMoves:number',
  'timeStr:string',
  'token:undefined',
  'tps:string',
  'unlockedCages:object',
  'unlockedCagesSortedArr:object',
  'unlockedCagesValues:object',
  'updateCurrentAverages:function',
  'updatePlaygroundStats:function',
  'userName:undefined',
  'userScrambleId:number',
  'walkSpeed:number',
  'wasAvgRecords:object',
  'wasReplay:boolean'
];

describe('useBaseStore public surface', () => {
  beforeEach(() => {
    localStorage.clear();
    setActivePinia(createPinia());
  });

  it('exposes exactly the documented members, with unchanged value/function kinds', () => {
    const store = useBaseStore() as unknown as Record<string, unknown>;
    const actual = Object.keys(store)
      .filter((key) => !key.startsWith('$') && !key.startsWith('_'))
      .sort((a, b) => a.localeCompare(b))
      .map((key) => `${key}:${typeof store[key]}`);
    expect(actual).toEqual(PUBLIC_SURFACE);
  });
});
